name: NodeJS with Webpack

on:
  pull_request:
  push:
    branches:
      - 'main'
      - '*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        sh build.sh
        npm run test

    - name: Make sure code conforms to prettier standards
      run: |
        npm run prettier-test
