name: NodeJS with Webpack

on:
  pull_request:
  push:
    branches:
      - 'main'
      - '*.*'
  workflow_dispatch:

env:
  DB_PASSWORD: gh-actions
  CONFIG_FILE_PATH: ../.github/workflows/ci.config.ini

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MARIADB_DATABASE: helios

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start API server
      run: |
        cd server
        python -m pip install -r requirements.txt
        python -m flask --app main run --debug &
        cd ..

    - name: Make sure package can be built
      run: |
        npm ci
        sh build.sh

    - name: Run javascript unit tests
      run: npm run test

    - name: Run python unit tests
      run: cd server && python -m pytest && cd ..

    - name: Make sure code conforms to prettier standards
      run: |
        npm run prettier-test
